// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SRP.Domain.Entities;

public partial class Address : BaseEntity
{
    public Guid AddressTypeId { get; set; }

    public int SlotIndex { get; set; }

    public string? Floor { get; set; }

    public string? Building { get; set; }

    public string Street { get; set; } = null!;

    public string City { get; set; } = null!;

    public string PostalCode { get; set; } = null!;

    public Guid? LocationId { get; set; }

    public Guid ProvinceId { get; set; }

    public Guid CountryId { get; set; }

    public virtual AddressType AddressType { get; set; } = null!;

    public virtual Country Country { get; set; } = null!;

    public virtual ICollection<LegalEntityAddressLink> LegalEntityAddressLink { get; set; } = new List<LegalEntityAddressLink>();

    public virtual Location? Location { get; set; }

    public virtual Province Province { get; set; } = null!;
}