// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SRP.Domain.Entities;

public partial class Application : BaseEntity
{
    public Guid ApplicantId { get; set; }

    public Guid? ApplicantTypeId { get; set; }

    public Guid? PreviousApplicationId { get; set; }

    public Guid? StatusId { get; set; }

    public string? ApplicationCode { get; set; }

    public string? SupplierCode { get; set; }

    public byte? ApplicationYear { get; set; }

    public DateTime? ValidityStartDate { get; set; }

    public DateTime? ValidityEndDate { get; set; }

    public DateTime? FirstApplyTS { get; set; }

    public DateTime? ApplyTS { get; set; }

    public DateTime? ApproveTS { get; set; }

    public DateTime? WelcomeMailTS { get; set; }

    public virtual ApplicantType? ApplicantType { get; set; }

    public virtual ICollection<LegalEntity> LegalEntity { get; set; } = new List<LegalEntity>();

    public virtual Status? Status { get; set; }
}