// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SRP.Domain.Entities;

public partial class Applicant : BaseEntity
{
    public Guid FileId { get; set; }

    public Guid? LegalEntityId { get; set; }

    public virtual File File { get; set; } = null!;
}