// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SRP.Domain.Entities;

public partial class Contact: BaseEntity
{
    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string FixedPhoneNumber { get; set; }

    public string MobileNumber { get; set; }

    public string WhatsAppNumber { get; set; }

    public string EmailAddress { get; set; }

    public virtual ICollection<LegalEntityContactLink> LegalEntityContactLink { get; set; } = new List<LegalEntityContactLink>();
}