// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SRP.Domain.Entities;

public partial class File : BaseEntity
{
    public string Code { get; set; } = null!;

    public string Name { get; set; } = null!;

    public virtual ICollection<Applicant> Applicant { get; set; } = new List<Applicant>();

    public virtual ICollection<Document> Document { get; set; } = new List<Document>();

    public virtual ICollection<FileUserLink> FileUserLink { get; set; } = new List<FileUserLink>();
}