// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SRP.Domain.Entities;

public partial class LegalEntity : BaseEntity
{
    public Guid FileId { get; set; }

    public Guid ApplicationId { get; set; }

    public Guid LegalEntityTypeId { get; set; }

    public string Name { get; set; }

    public string TradingName { get; set; }

    public string RegistrationNumber { get; set; }

    public string IdentificationNumber { get; set; }

    public bool? IsBEECertified { get; set; }

    public Guid? BEECertificationTypeId { get; set; }

    public string BEECertificationDetails { get; set; }

    public Guid LocalMunicipalityId { get; set; }

    public string LocalMunicpalityAccountNumber { get; set; }

    public int CommunicationMethodId { get; set; }

    public virtual Application Application { get; set; }

    public virtual ICollection<Document> Document { get; set; } = new List<Document>();

    public virtual ICollection<LegalEntityAddressLink> LegalEntityAddressLink { get; set; } = new List<LegalEntityAddressLink>();

    public virtual ICollection<LegalEntityContactLink> LegalEntityContactLink { get; set; } = new List<LegalEntityContactLink>();

    public virtual LegalEntityType LegalEntityType { get; set; }

    public virtual LocalMunicipality LocalMunicipality { get; set; }
}