// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SRP.Domain.Entities;

public partial class LocalMunicipality : BaseEntity
{
    public string Code { get; set; }

    public string Name { get; set; }

    public virtual ICollection<LegalEntity> LegalEntity { get; set; } = new List<LegalEntity>();
}