// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SRP.Domain.Entities;

public partial class Province : BaseEntity
{
    public Guid CountryId { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<Address> Address { get; set; } = new List<Address>();

    public virtual Country Country { get; set; } = null!;

    public virtual ICollection<Location> Location { get; set; } = new List<Location>();
}