// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SRP.Domain.Entities;

public partial class Title : BaseEntity
{
    public string Code { get; set; } = null!;

    public string? Description { get; set; }
}